name: Python application

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build docker image for FastAPI
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/movie-ml-test:${{github.sha}} .

      - name: Logging to the Docker Hub
        run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login --username "${{secrets.DOCKER_USERNAME}}" --password-stdin

      - name: Push the image to Docker Hub
        run: docker push ${{secrets.DOCKER_USERNAME}}/movie-ml-test:${{github.sha}}
