# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build docker image for FastAPI
        run: docker build -t '${{secrets.DOCKER_USERNAME}}'/movie-ml-test:'${{github.sha}}' .

      - name: Logging to the Docker hub
        run: docker login --username '${{secrets.DOCKER_USERNAME}}' --password '${{secrets.DOCKER_PASSWORD}}'

      - name: Push the image to the docker hub
        run: docker push '${{secrets.DOCKER_USERNAME}}'/movie-ml-test:'${{github.sha}}'


      # Deploy Docker image to EC2
      - name: Deploy to EC2
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            EC2_HOST: ${{ secrets.EC2_HOST }}  # EC2 Public IP
            EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}  # Private key for SSH access
        run: |
            # Install dependencies
            sudo apt-get update
            sudo apt-get install -y ssh

            # Save the private key to a file
            echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
            chmod 600 private_key.pem

            # SSH into EC2 and deploy Docker container
            ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
                docker pull ${{ secrets.DOCKER_USERNAME }}/movie-ml-test:${{ github.sha }}
                docker stop movie-ml-test || true
                docker rm movie-ml-test || true
                docker run -d --name movie-ml-test -p 80:80 ${{ secrets.DOCKER_USERNAME }}/movie-ml-test:${{ github.sha }}
            EOF
